production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    auto_commit_after_request: false
    auto_commit_after_delete_request: true

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    auto_commit_after_request: false
    auto_commit_after_delete_request: true

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    auto_commit_after_request: false
    auto_commit_after_delete_request: true